[pytest]
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function

testpaths =
    tests

python_files = test_*.py
python_functions = test_*

addopts =
    -q
    --disable-warnings
    --basetemp=runtime/test_tmp

filterwarnings =
    ignore:Using httpx with starlette.testclient is deprecated:DeprecationWarning
norecursedirs = tests/_quarantine_dead_imports
