from enum import Enum

class AuditAction(str, Enum):
    # Capability Actions
    VALIDATE_TOKEN = "VALIDATE_TOKEN"
    REVOKE_TOKEN = "REVOKE_TOKEN"
    EXPIRE_TOKEN = "EXPIRE_TOKEN"
    
    # Execution Actions
    EXECUTION_REQUESTED = "EXECUTION_REQUESTED"
    EXECUTION_AUTHORIZED = "EXECUTION_AUTHORIZED"
    EXECUTION_BLOCKED = "EXECUTION_BLOCKED"
    EXECUTION_COMPLETED = "EXECUTION_COMPLETED"
    
    # Memory Actions (Préparation 2.4.6)
    MEMORY_WRITE = "MEMORY_WRITE"
    MEMORY_READ = "MEMORY_READ"
    MEMORY_EXPIRE = "MEMORY_EXPIRE"
    MEMORY_DELETE = "MEMORY_DELETE"
