plugins {
    id 'com.android.application'
}

android {
    namespace 'ai.ezzio.office'
    compileSdk 34

    defaultConfig {
        applicationId "ai.ezzio.office"
        minSdk 26
        targetSdk 34
        versionCode 901
        versionName "9.0.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file("release.keystore")
            storePassword "ezzio_release_key_2026"
            keyAlias "ezzio"
            keyPassword "ezzio_release_key_2026"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
